homeassistant:
  # name: Home Assistant
  # latitude: 
  # longitude: 
  # elevation: 3
  # unit_system: metric
  # time_zone: Asia/Shanghai
  # external_url:             ## 填入自己的外部访问地址
  # internal_url:             ## 填入局域网地址
  currency: CNY
  packages: !include_dir_named packages/


frontend:
  themes: !include_dir_merge_named themes

lovelace:
  mode: storage
  dashboards:
    homekit-infused:
      mode: yaml
      title: 主页
      icon: mdi:monitor-cellphone
      show_in_sidebar: true
      filename: "hki-base/homekit-infused.yaml"

    neon-lovelace:
      mode: yaml
      title: Neon Lovelace
      icon: mdi:tablet-android
      show_in_sidebar: true
      filename: dashboards/neon/ui-lovelace.yaml

    mattias-lovelace:
      mode: yaml
      title: Mattias Lovelace
      icon: mdi:tablet-cellphone
      show_in_sidebar: true
      filename: dashboards/tablet/ui-lovelace.yaml